export function getCountryData(
  code: string,
): { name: string; flagUrl: string } | undefined {
  const countryCodes: Record<string, { name: string; flagUrl: string }> = {
    AFG: { name: 'Afghanistan', flagUrl: 'https://flagcdn.com/af.svg' },
    AHO: { name: 'Netherlands Antilles', flagUrl: 'https://flagcdn.com/an.svg' },
    ALB: { name: 'Albania', flagUrl: 'https://flagcdn.com/al.svg' },
    ALG: { name: 'Algeria', flagUrl: 'https://flagcdn.com/dz.svg' },
    AND: { name: 'Andorra', flagUrl: 'https://flagcdn.com/ad.svg' },
    ANG: { name: 'Angola', flagUrl: 'https://flagcdn.com/ao.svg' },
    ANT: { name: 'Antigua and Barbuda', flagUrl: 'https://flagcdn.com/ag.svg' },
    ANZ: { name: 'Australasia', flagUrl: 'https://flagcdn.com/au.svg' },
    ARG: { name: 'Argentina', flagUrl: 'https://flagcdn.com/ar.svg' },
    ARM: { name: 'Armenia', flagUrl: 'https://flagcdn.com/am.svg' },
    ARU: { name: 'Aruba', flagUrl: 'https://flagcdn.com/aw.svg' },
    ASA: { name: 'American Samoa', flagUrl: 'https://flagcdn.com/as.svg' },
    AUS: { name: 'Australia', flagUrl: 'https://flagcdn.com/au.svg' },
    AUT: { name: 'Austria', flagUrl: 'https://flagcdn.com/at.svg' },
    AZE: { name: 'Azerbaijan', flagUrl: 'https://flagcdn.com/az.svg' },
    BHS: { name: 'Bahamas', flagUrl: 'https://flagcdn.com/bs.svg' },
    BHR: { name: 'Bahrain', flagUrl: 'https://flagcdn.com/bh.svg' },
    BGD: { name: 'Bangladesh', flagUrl: 'https://flagcdn.com/bd.svg' },
    BRB: { name: 'Barbados', flagUrl: 'https://flagcdn.com/bb.svg' },
    BLR: { name: 'Belarus', flagUrl: 'https://flagcdn.com/by.svg' },
    BEL: { name: 'Belgium', flagUrl: 'https://flagcdn.com/be.svg' },
    BLZ: { name: 'Belize', flagUrl: 'https://flagcdn.com/bz.svg' },
    BEN: { name: 'Benin', flagUrl: 'https://flagcdn.com/bj.svg' },
    BTN: { name: 'Bhutan', flagUrl: 'https://flagcdn.com/bt.svg' },
    BOL: {
      name: 'Bolivia (Plurinational State of)',
      flagUrl: 'https://flagcdn.com/bo.svg',
    },
    BIH: { name: 'Bosnia and Herzegovina', flagUrl: 'https://flagcdn.com/ba.svg' },
    BWA: { name: 'Botswana', flagUrl: 'https://flagcdn.com/bw.svg' },
    BRA: { name: 'Brazil', flagUrl: 'https://flagcdn.com/br.svg' },
    BRN: { name: 'Brunei Darussalam', flagUrl: 'https://flagcdn.com/bn.svg' },
    BGR: { name: 'Bulgaria', flagUrl: 'https://flagcdn.com/bg.svg' },
    BFA: { name: 'Burkina Faso', flagUrl: 'https://flagcdn.com/bf.svg' },
    BDI: { name: 'Burundi', flagUrl: 'https://flagcdn.com/bi.svg' },
    CPV: { name: 'Cabo Verde', flagUrl: 'https://flagcdn.com/cv.svg' },
    KHM: { name: 'Cambodia', flagUrl: 'https://flagcdn.com/kh.svg' },
    CMR: { name: 'Cameroon', flagUrl: 'https://flagcdn.com/cm.svg' },
    CAN: { name: 'Canada', flagUrl: 'https://flagcdn.com/ca.svg' },
    CAF: { name: 'Central African Republic', flagUrl: 'https://flagcdn.com/cf.svg' },
    TCD: { name: 'Chad', flagUrl: 'https://flagcdn.com/td.svg' },
    CHL: { name: 'Chile', flagUrl: 'https://flagcdn.com/cl.svg' },
    CHN: { name: 'China', flagUrl: 'https://flagcdn.com/cn.svg' },
    COL: { name: 'Colombia', flagUrl: 'https://flagcdn.com/co.svg' },
    COM: { name: 'Comoros', flagUrl: 'https://flagcdn.com/km.svg' },
    COG: { name: 'Congo', flagUrl: 'https://flagcdn.com/cg.svg' },
    COD: {
      name: 'Congo (Democratic Republic of the)',
      flagUrl: 'https://flagcdn.com/cd.svg',
    },
    CRI: { name: 'Costa Rica', flagUrl: 'https://flagcdn.com/cr.svg' },
    CIV: { name: "CÃ´te d'Ivoire", flagUrl: 'https://flagcdn.com/ci.svg' },
    HRV: { name: 'Croatia', flagUrl: 'https://flagcdn.com/hr.svg' },
    CUB: { name: 'Cuba', flagUrl: 'https://flagcdn.com/cu.svg' },
    CYP: { name: 'Cyprus', flagUrl: 'https://flagcdn.com/cy.svg' },
    CZE: { name: 'Czech Republic', flagUrl: 'https://flagcdn.com/cz.svg' },
    DNK: { name: 'Denmark', flagUrl: 'https://flagcdn.com/dk.svg' },
    DJI: { name: 'Djibouti', flagUrl: 'https://flagcdn.com/dj.svg' },
    DMA: { name: 'Dominica', flagUrl: 'https://flagcdn.com/dm.svg' },
    DOM: { name: 'Dominican Republic', flagUrl: 'https://flagcdn.com/do.svg' },
    ECU: { name: 'Ecuador', flagUrl: 'https://flagcdn.com/ec.svg' },
    EGY: { name: 'Egypt', flagUrl: 'https://flagcdn.com/eg.svg' },
    SLV: { name: 'El Salvador', flagUrl: 'https://flagcdn.com/sv.svg' },
    GNQ: { name: 'Equatorial Guinea', flagUrl: 'https://flagcdn.com/gq.svg' },
    ERI: { name: 'Eritrea', flagUrl: 'https://flagcdn.com/er.svg' },
    EST: { name: 'Estonia', flagUrl: 'https://flagcdn.com/ee.svg' },
    SWZ: { name: 'Eswatini', flagUrl: 'https://flagcdn.com/sz.svg' },
    ETH: { name: 'Ethiopia', flagUrl: 'https://flagcdn.com/et.svg' },
    FJI: { name: 'Fiji', flagUrl: 'https://flagcdn.com/fj.svg' },
    FIN: { name: 'Finland', flagUrl: 'https://flagcdn.com/fi.svg' },
    FRA: { name: 'France', flagUrl: 'https://flagcdn.com/fr.svg' },
    GAB: { name: 'Gabon', flagUrl: 'https://flagcdn.com/ga.svg' },
    GMB: { name: 'Gambia', flagUrl: 'https://flagcdn.com/gm.svg' },
    GEO: { name: 'Georgia', flagUrl: 'https://flagcdn.com/ge.svg' },
    DEU: { name: 'Germany', flagUrl: 'https://flagcdn.com/de.svg' },
    GHA: { name: 'Ghana', flagUrl: 'https://flagcdn.com/gh.svg' },
    GRC: { name: 'Greece', flagUrl: 'https://flagcdn.com/gr.svg' },
    GRD: { name: 'Grenada', flagUrl: 'https://flagcdn.com/gd.svg' },
    GTM: { name: 'Guatemala', flagUrl: 'https://flagcdn.com/gt.svg' },
    GIN: { name: 'Guinea', flagUrl: 'https://flagcdn.com/gn.svg' },
    GNB: { name: 'Guinea-Bissau', flagUrl: 'https://flagcdn.com/gw.svg' },
    GUY: { name: 'Guyana', flagUrl: 'https://flagcdn.com/gy.svg' },
    HTI: { name: 'Haiti', flagUrl: 'https://flagcdn.com/ht.svg' },
    HND: { name: 'Honduras', flagUrl: 'https://flagcdn.com/hn.svg' },
    HUN: { name: 'Hungary', flagUrl: 'https://flagcdn.com/hu.svg' },
    ISL: { name: 'Iceland', flagUrl: 'https://flagcdn.com/is.svg' },
    IND: { name: 'India', flagUrl: 'https://flagcdn.com/in.svg' },
    IDN: { name: 'Indonesia', flagUrl: 'https://flagcdn.com/id.svg' },
    IRN: { name: 'Iran (Islamic Republic of)', flagUrl: 'https://flagcdn.com/ir.svg' },
    IRQ: { name: 'Iraq', flagUrl: 'https://flagcdn.com/iq.svg' },
    IRL: { name: 'Ireland', flagUrl: 'https://flagcdn.com/ie.svg' },
    ISR: { name: 'Israel', flagUrl: 'https://flagcdn.com/il.svg' },
    ITA: { name: 'Italy', flagUrl: 'https://flagcdn.com/it.svg' },
    JAM: { name: 'Jamaica', flagUrl: 'https://flagcdn.com/jm.svg' },
    JPN: { name: 'Japan', flagUrl: 'https://flagcdn.com/jp.svg' },
    JOR: { name: 'Jordan', flagUrl: 'https://flagcdn.com/jo.svg' },
    KAZ: { name: 'Kazakhstan', flagUrl: 'https://flagcdn.com/kz.svg' },
    KEN: { name: 'Kenya', flagUrl: 'https://flagcdn.com/ke.svg' },
    KIR: { name: 'Kiribati', flagUrl: 'https://flagcdn.com/ki.svg' },
    PRK: {
      name: "Korea (Democratic People's Republic of)",
      flagUrl: 'https://flagcdn.com/kp.svg',
    },
    KOR: { name: 'Korea (Republic of)', flagUrl: 'https://flagcdn.com/kr.svg' },
    KWT: { name: 'Kuwait', flagUrl: 'https://flagcdn.com/kw.svg' },
    KGZ: { name: 'Kyrgyzstan', flagUrl: 'https://flagcdn.com/kg.svg' },
    LAO: {
      name: "Lao People's Democratic Republic",
      flagUrl: 'https://flagcdn.com/la.svg',
    },
    LVA: { name: 'Latvia', flagUrl: 'https://flagcdn.com/lv.svg' },
    LBN: { name: 'Lebanon', flagUrl: 'https://flagcdn.com/lb.svg' },
    LSO: { name: 'Lesotho', flagUrl: 'https://flagcdn.com/ls.svg' },
    LBR: { name: 'Liberia', flagUrl: 'https://flagcdn.com/lr.svg' },
    LBY: { name: 'Libya', flagUrl: 'https://flagcdn.com/ly.svg' },
    LIE: { name: 'Liechtenstein', flagUrl: 'https://flagcdn.com/li.svg' },
    LTU: { name: 'Lithuania', flagUrl: 'https://flagcdn.com/lt.svg' },
    LUX: { name: 'Luxembourg', flagUrl: 'https://flagcdn.com/lu.svg' },
    MDG: { name: 'Madagascar', flagUrl: 'https://flagcdn.com/mg.svg' },
    MWI: { name: 'Malawi', flagUrl: 'https://flagcdn.com/mw.svg' },
    MYS: { name: 'Malaysia', flagUrl: 'https://flagcdn.com/my.svg' },
    MDV: { name: 'Maldives', flagUrl: 'https://flagcdn.com/mv.svg' },
    MLI: { name: 'Mali', flagUrl: 'https://flagcdn.com/ml.svg' },
    MLT: { name: 'Malta', flagUrl: 'https://flagcdn.com/mt.svg' },
    MHL: { name: 'Marshall Islands', flagUrl: 'https://flagcdn.com/mh.svg' },
    MRT: { name: 'Mauritania', flagUrl: 'https://flagcdn.com/mr.svg' },
    MUS: { name: 'Mauritius', flagUrl: 'https://flagcdn.com/mu.svg' },
    MEX: { name: 'Mexico', flagUrl: 'https://flagcdn.com/mx.svg' },
    FSM: {
      name: 'Micronesia (Federated States of)',
      flagUrl: 'https://flagcdn.com/fm.svg',
    },
    MDA: { name: 'Moldova (Republic of)', flagUrl: 'https://flagcdn.com/md.svg' },
    MCO: { name: 'Monaco', flagUrl: 'https://flagcdn.com/mc.svg' },
    MNG: { name: 'Mongolia', flagUrl: 'https://flagcdn.com/mn.svg' },
    MNE: { name: 'Montenegro', flagUrl: 'https://flagcdn.com/me.svg' },
    MAR: { name: 'Morocco', flagUrl: 'https://flagcdn.com/ma.svg' },
    MOZ: { name: 'Mozambique', flagUrl: 'https://flagcdn.com/mz.svg' },
    MMR: { name: 'Myanmar', flagUrl: 'https://flagcdn.com/mm.svg' },
    NAM: { name: 'Namibia', flagUrl: 'https://flagcdn.com/na.svg' },
    NRU: { name: 'Nauru', flagUrl: 'https://flagcdn.com/nr.svg' },
    NPL: { name: 'Nepal', flagUrl: 'https://flagcdn.com/np.svg' },
    NLD: { name: 'Netherlands', flagUrl: 'https://flagcdn.com/nl.svg' },
    NZL: { name: 'New Zealand', flagUrl: 'https://flagcdn.com/nz.svg' },
    NIC: { name: 'Nicaragua', flagUrl: 'https://flagcdn.com/ni.svg' },
    NER: { name: 'Niger', flagUrl: 'https://flagcdn.com/ne.svg' },
    NGA: { name: 'Nigeria', flagUrl: 'https://flagcdn.com/ng.svg' },
    MKD: { name: 'North Macedonia', flagUrl: 'https://flagcdn.com/mk.svg' },
    NOR: { name: 'Norway', flagUrl: 'https://flagcdn.com/no.svg' },
    OMN: { name: 'Oman', flagUrl: 'https://flagcdn.com/om.svg' },
    PAK: { name: 'Pakistan', flagUrl: 'https://flagcdn.com/pk.svg' },
    PLW: { name: 'Palau', flagUrl: 'https://flagcdn.com/pw.svg' },
    PAN: { name: 'Panama', flagUrl: 'https://flagcdn.com/pa.svg' },
    PNG: { name: 'Papua New Guinea', flagUrl: 'https://flagcdn.com/pg.svg' },
    PRY: { name: 'Paraguay', flagUrl: 'https://flagcdn.com/py.svg' },
    PER: { name: 'Peru', flagUrl: 'https://flagcdn.com/pe.svg' },
    PHL: { name: 'Philippines', flagUrl: 'https://flagcdn.com/ph.svg' },
    POL: { name: 'Poland', flagUrl: 'https://flagcdn.com/pl.svg' },
    PRT: { name: 'Portugal', flagUrl: 'https://flagcdn.com/pt.svg' },
    QAT: { name: 'Qatar', flagUrl: 'https://flagcdn.com/qa.svg' },
    ROU: { name: 'Romania', flagUrl: 'https://flagcdn.com/ro.svg' },
    RUS: { name: 'Russian Federation', flagUrl: 'https://flagcdn.com/ru.svg' },
    RWA: { name: 'Rwanda', flagUrl: 'https://flagcdn.com/rw.svg' },
    KNA: { name: 'Saint Kitts and Nevis', flagUrl: 'https://flagcdn.com/kn.svg' },
    LCA: { name: 'Saint Lucia', flagUrl: 'https://flagcdn.com/lc.svg' },
    VCT: {
      name: 'Saint Vincent and the Grenadines',
      flagUrl: 'https://flagcdn.com/vc.svg',
    },
    WSM: { name: 'Samoa', flagUrl: 'https://flagcdn.com/ws.svg' },
    SMR: { name: 'San Marino', flagUrl: 'https://flagcdn.com/sm.svg' },
    STP: { name: 'Sao Tome and Principe', flagUrl: 'https://flagcdn.com/st.svg' },
    SAU: { name: 'Saudi Arabia', flagUrl: 'https://flagcdn.com/sa.svg' },
    SEN: { name: 'Senegal', flagUrl: 'https://flagcdn.com/sn.svg' },
    SRB: { name: 'Serbia', flagUrl: 'https://flagcdn.com/rs.svg' },
    SYC: { name: 'Seychelles', flagUrl: 'https://flagcdn.com/sc.svg' },
    SLE: { name: 'Sierra Leone', flagUrl: 'https://flagcdn.com/sl.svg' },
    SGP: { name: 'Singapore', flagUrl: 'https://flagcdn.com/sg.svg' },
    SVK: { name: 'Slovakia', flagUrl: 'https://flagcdn.com/sk.svg' },
    SVN: { name: 'Slovenia', flagUrl: 'https://flagcdn.com/si.svg' },
    SLB: { name: 'Solomon Islands', flagUrl: 'https://flagcdn.com/sb.svg' },
    SOM: { name: 'Somalia', flagUrl: 'https://flagcdn.com/so.svg' },
    ZAF: { name: 'South Africa', flagUrl: 'https://flagcdn.com/za.svg' },
    SSD: { name: 'South Sudan', flagUrl: 'https://flagcdn.com/ss.svg' },
    ESP: { name: 'Spain', flagUrl: 'https://flagcdn.com/es.svg' },
    LKA: { name: 'Sri Lanka', flagUrl: 'https://flagcdn.com/lk.svg' },
    SDN: { name: 'Sudan', flagUrl: 'https://flagcdn.com/sd.svg' },
    SUR: { name: 'Suriname', flagUrl: 'https://flagcdn.com/sr.svg' },
    SWE: { name: 'Sweden', flagUrl: 'https://flagcdn.com/se.svg' },
    CHE: { name: 'Switzerland', flagUrl: 'https://flagcdn.com/ch.svg' },
    SYR: { name: 'Syrian Arab Republic', flagUrl: 'https://flagcdn.com/sy.svg' },
    TWN: { name: 'Taiwan (Province of China)', flagUrl: 'https://flagcdn.com/tw.svg' },
    TJK: { name: 'Tajikistan', flagUrl: 'https://flagcdn.com/tj.svg' },
    TZA: { name: 'Tanzania (United Republic of)', flagUrl: 'https://flagcdn.com/tz.svg' },
    THA: { name: 'Thailand', flagUrl: 'https://flagcdn.com/th.svg' },
    TLS: { name: 'Timor-Leste', flagUrl: 'https://flagcdn.com/tl.svg' },
    TGO: { name: 'Togo', flagUrl: 'https://flagcdn.com/tg.svg' },
    TON: { name: 'Tonga', flagUrl: 'https://flagcdn.com/to.svg' },
    TTO: { name: 'Trinidad and Tobago', flagUrl: 'https://flagcdn.com/tt.svg' },
    TUN: { name: 'Tunisia', flagUrl: 'https://flagcdn.com/tn.svg' },
    TUR: { name: 'Turkey', flagUrl: 'https://flagcdn.com/tr.svg' },
    TKM: { name: 'Turkmenistan', flagUrl: 'https://flagcdn.com/tm.svg' },
    TUV: { name: 'Tuvalu', flagUrl: 'https://flagcdn.com/tv.svg' },
    UGA: { name: 'Uganda', flagUrl: 'https://flagcdn.com/ug.svg' },
    UKR: { name: 'Ukraine', flagUrl: 'https://flagcdn.com/ua.svg' },
    ARE: { name: 'United Arab Emirates', flagUrl: 'https://flagcdn.com/ae.svg' },
    GBR: {
      name: 'United Kingdom of Great Britain and Northern Ireland',
      flagUrl: 'https://flagcdn.com/gb.svg',
    },
    USA: { name: 'United States of America', flagUrl: 'https://flagcdn.com/us.svg' },
    URY: { name: 'Uruguay', flagUrl: 'https://flagcdn.com/uy.svg' },
    UZB: { name: 'Uzbekistan', flagUrl: 'https://flagcdn.com/uz.svg' },
    VUT: { name: 'Vanuatu', flagUrl: 'https://flagcdn.com/vu.svg' },
    VEN: {
      name: 'Venezuela (Bolivarian Republic of)',
      flagUrl: 'https://flagcdn.com/ve.svg',
    },
    VNM: { name: 'Viet Nam', flagUrl: 'https://flagcdn.com/vn.svg' },
    YEM: { name: 'Yemen', flagUrl: 'https://flagcdn.com/ye.svg' },
    ZMB: { name: 'Zambia', flagUrl: 'https://flagcdn.com/zm.svg' },
    ZWE: { name: 'Zimbabwe', flagUrl: 'https://flagcdn.com/zw.svg' },
  };

  return countryCodes[code];
}
