name: Build and deploy website

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "front/**"

jobs:
  build:
    uses: ./.github/workflows/build_frontend.yml
    secrets: inherit
  deploy:
    needs: build
    uses: ./.github/workflows/deploy_frontend.yml
    secrets: inherit
