name: Build olympics-api

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "database/**"
      - "api/**"

jobs:
  deploy_db:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Remove old cached db data
        run: |
          rm -rf /Apps/containerDatas/olympics/docker
      - name: Remove old containers
        run: |
          docker-compose -f api.docker-compose.yml down
          docker image prune -f
      - name: Create .env file
        run: |
          echo "${{ secrets.API_ENV_FILE }}" >> api.env
      - name: build DB
        run: |
          docker-compose --env-file api.env -f api.docker-compose.yml -p "olympics-api" up --build -d
