name: Linting and testing
on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          #Branch of PR or input tag or default to main
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        run: cd front && npm install
      - name: Lint code
        run: cd front && npm run lint
